services:
  db:
    image: postgres:14-alpine
    container_name: revenda-db
    restart: always
    environment:
      - POSTGRES_USER=postech
      - POSTGRES_PASSWORD=soat123
      - POSTGRES_DB=revenda_veiculos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postech -d revenda_veiculos"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    container_name: revenda-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/revenda_veiculos
      - SPRING_DATASOURCE_USERNAME=postech
      - SPRING_DATASOURCE_PASSWORD=soat123
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: {}